version: '3.0'

services:
  node:
    image: node:20.12.2-alpine
    working_dir: /var/opt/app
    volumes:
      - .:/var/opt/app
      - ../../:/var/opt/megalodon
    ports:
      - "8000:8000"
    command: /bin/sh
